/** Shared option lists for admin ticket create/edit forms. */

export const TICKET_TYPES = [
  'config_remediation',
  'config_diff',
  'scripting',
  'python',
  'shell',
  'sysadmin',
  'cccer',
  'hybrid',
  'tool_walkthrough',
  'simplerisk',
  'simplerisk_walkthrough',
  'control_mapping',
  'oscal_ssp',
  'ssp',
  'assessment_procedures',
  'sp800_53a',
  'sp_800_53a',
  'poam',
  'poam_draft',
  'sec_materiality',
  'sec_cyber_materiality',
  'conmon_strategy',
  'continuous_monitoring',
  'oscal_generator',
  'capstone_oscal',
  'cmmc_gap_analysis',
  'cmmc_l2_gap',
  'authorization_package',
  'ao_review',
] as const;

export const DIFFICULTIES = ['critical', 'high', 'medium', 'low'] as const;
